### ISSUE TITLE
Create Listing Logic

### ISSUE THREAD

**Issue by SirHertzAlot** [SirHertzAlot/commerce#9]
## Tasks:
- [x] Create Listing: Users should be able to visit a page to create a new listing. 
  ## Subtasks:
    - [x] They should be able to specify a title for the listing, a text-based description, and what the starting bid should be. 
    - [ ] Users should also optionally be able to provide a URL for an image for the listing and/or a category (e.g. Fashion, Toys, Electronics, Home, etc.).
